### ISSUE TITLE
Component の型定義周りの書き方を統一する

### ISSUE THREAD

**Issue by hapo31** [LipersInSlums/LipersInSlums.github.io#3]
今のところ 2x3x2 通りぐらいあって、

- Functional Component の戻り値の書き方
  - `React.FC<Props>`派
  - 何も書かない派
- Props の型定義の書き方
  - type 派
  - interface 派
  - 書かないで引数で直接定義
 - Component の定義の仕方
   - `function Component() {}` 派
   - `const Component = () => {}` 派
   - ~Class Component派は絶滅しました~

という三国志もビックリの混沌さ（おおげさ）

ちなみに、上のパターンのうち1つは Next.js が生成したもの。(pages/_app.tsx)
```tsx
const App = (props: AppProps) => {
```

ここではいくつか数パターンに絞ってどれに統一するか議論したい。
以下はパターンの叩き台。
他に案があればコメントへ。

# A
```tsx
import { FC } from "react";

type Props = { ... }

const Component: FC<Props> = ({ a, b }) => { ... }
```

# B
```tsx
type Props = { ... }

const Component = ({ a, b }: Props) => { ... }
```

# C
```tsx
const Component = (props: { a: number, b: number, ... } ) => { ... }
```

**Comment by skht777** [comment]
Aかな

**Comment by Lugendre** [comment]
Aでいいと思う too

Propsをtypeで書くのも勝手に拡張されて困るからinterfaceを避けるみたいな方向にとりあえず倒しておくでいいと思う
